### PR TITLE
WIP: Server-side page max checking

### PR DESCRIPTION
**Pull request by lol768**
Problems:

* Redirects transparently followed by browser, `go(xhr.getResponseHeader('Location'));` doesn't work because Play returns a redirect.

### CODE REVIEW

**Comment by lol768** [comment]
Why is this done with AJAX anyway?

**Comment by simon816** [comment]
Looks like it's done with AJAX because of the javascript logic before the request

**Comment by lol768** [comment]
>Looks like it's done with AJAX because of the javascript logic before the request

Can you think of any reason why I can't implement this in the controller?

**Comment by simon816** [comment]
You probably could do it in the controller and just have a form instead

**Comment by vectrixdevelops** [comment]
@lol768 Any update on this?

**Comment by lol768** [comment]
@connorhartley 

Unlikely to have time to finish this on top of my security consulting work, sorry.

If anyone wants to pick this up, I suggest you remove the unnecessary AJAX and do this with a POST properly. You can probably reuse the code I have in the controller, it'll be a case of making the frontend stuff form-based.

**Comment by lol768** [comment]
RIP

**Pull request closed without merging**
